### PR TITLE
Use only one of 'verbose' and 'silent' parameters to model.

### PR DESCRIPTION
**Pull request by alaneckhardt**
Fixing #78 .

### CODE REVIEW

**Comment by HunterMcGushion** [comment]
Thanks for catching these! This PR also addresses the separate issue #80, correct?

**Comment by alaneckhardt** [comment]
Ouch, yes.
I didn't mean to include both commits in the pull request, since I'm not sure about the behaviour of other models with respect to `silent` and `verbose` parameters.

**Comment by HunterMcGushion** [comment]
No worries! Yeah that's the part I need to do a little more digging on, as well. If it makes sense for you, you could split the changes into two PRs. That way we can merge the changes from faf90c1 sooner, while I figure out what might be affected by 39185f5 before merging it. 
Let me know what you think, and thanks again for your contributions!

**Comment by HunterMcGushion** [comment]
Also, if you'd like, you can add yourself to the list of contributors in AUTHORS.md. Otherwise, I'd be happy to do it myself later.

**Comment by alaneckhardt** [comment]
I changed this MR to address the CatBoost issue and create #81 for holdout set. 
I really don't feel being added to authors :)

**Comment by HunterMcGushion** [comment]
This looks great! Thanks for catching this bug, @alaneckhardt!

**Pull request merged**
